a=input("enter house holder name")
b=input("enter a house / door no")
c=input("street name")
d=input("near by landmark")
e = input("your district")
f=input("Your state")
g=int(input("enter pincode"))
print(a,",",b,",",c,",",d,",",e,",",f,",",g)        